swagger: '2.0'
info:
  version: v1
  title: ACR HL7 Listener
  description: Service for receiving HL7 messages
  extensions: {}
paths:
  /api/Listeners:
    get:
      tags:
      - Listeners
      summary: Gets all available listeners
      description: Obtains all available listeners for the running service.
      operationId: GetListeners
      consumes: []
      produces: []
      parameters: []
      responses:
        200:
          description: Returns the available listeners
          extensions: {}
        500:
          description: Bad input parameter
          extensions: {}
      extensions: {}
    post:
      tags:
      - Listeners
      operationId: PostListener
      consumes:
      - application/json-patch+json
      - application/json
      - text/json
      - application/*+json
      produces:
      - text/plain
      - application/json
      - text/json
      parameters:
      - name: listener
        in: body
        extensions: {}
        schema:
          ref: '#/definitions/HL7MessageListener'
          extensions: {}
      responses:
        200:
          description: Success
          schema:
            ref: '#/definitions/HL7MessageListener'
            extensions: {}
          extensions: {}
      extensions: {}
    extensions: {}
  /api/Listeners/{id}:
    get:
      tags:
      - Listeners
      operationId: GetListener
      consumes: []
      produces: []
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int32
        extensions: {}
      responses:
        200:
          description: Success
          extensions: {}
      extensions: {}
    put:
      tags:
      - Listeners
      operationId: PutListener
      consumes:
      - application/json-patch+json
      - application/json
      - text/json
      - application/*+json
      produces: []
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int32
        extensions: {}
      - name: listener
        in: body
        extensions: {}
        schema:
          ref: '#/definitions/HL7MessageListener'
          extensions: {}
      responses:
        200:
          description: Success
          extensions: {}
      extensions: {}
    delete:
      tags:
      - Listeners
      operationId: DeleteListener
      consumes: []
      produces:
      - text/plain
      - application/json
      - text/json
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int32
        extensions: {}
      responses:
        200:
          description: Success
          schema:
            ref: '#/definitions/HL7MessageListener'
            extensions: {}
          extensions: {}
      extensions: {}
    extensions: {}
  /api/Logs:
    get:
      tags:
      - Logs
      operationId: Get
      consumes: []
      produces: []
      parameters: []
      responses:
        200:
          description: Success
          extensions: {}
      extensions: {}
    extensions: {}
  /api/Logs/in/{seconds}:
    get:
      tags:
      - Logs
      summary: Get list of all logs with in a timespan of give senconds.
      operationId: GetWithin
      consumes: []
      produces: []
      parameters:
      - name: seconds
        in: path
        description: Specify number of seconds, to retrieve all recent logs logged in the timespan.
        required: true
        type: integer
        format: int32
        extensions: {}
      responses:
        200:
          description: Success
          extensions: {}
      extensions: {}
    extensions: {}
  /api/Status/healthcheck:
    get:
      tags:
      - Status
      operationId: HealthCheck
      consumes: []
      produces: []
      parameters: []
      responses:
        200:
          description: Success
          extensions: {}
      extensions: {}
    extensions: {}
  /api/Status/version:
    get:
      tags:
      - Status
      operationId: Version
      consumes: []
      produces: []
      parameters: []
      responses:
        200:
          description: Success
          extensions: {}
      extensions: {}
    extensions: {}
definitions:
  HL7MessageListener:
    type: object
    properties:
      id:
        format: int32
        type: integer
        extensions: {}
      ipAddress:
        type: string
        extensions: {}
      port:
        format: int32
        type: integer
        extensions: {}
      name:
        type: string
        extensions: {}
      status:
        format: int32
        enum:
        - Idle
        - Listening
        type: integer
        extensions: {}
    example:
      id: 1
      iPAddress: 0.0.0.0
      port: 50500
      name: Test HL7
    extensions: {}
extensions: {}
