swagger: '2.0'
info:
  version: v1
  title: ACR HL7 Listener
  description: Service for receiving HL7 messages
  
paths:
  /api/Listeners:
    get:
      tags:
      - Listeners
      summary: Gets all available listeners
      description: Obtains all available listeners for the running service.
      operationId: GetListeners
      consumes: []
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: Returns the available listeners
          schema:
            uniqueItems: false
            type: array
            items:
              $ref: '#/definitions/HL7MessageListener'
              
            
          
        500:
          description: Bad input parameter
          
      
    post:
      tags:
      - Listeners
      summary: Adds a listener
      description: Adds a listener.
      operationId: PostListener
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: listener
        in: body
        
        schema:
          $ref: '#/definitions/HL7MessageListener'
          
      responses:
        201:
          description: Listener created
          schema:
            $ref: '#/definitions/HL7MessageListener'
            
          
        500:
          description: Server error
          
      
    
  /api/Listeners/{id}:
    get:
      tags:
      - Listeners
      summary: Adds a listener
      description: Adds a listener.
      operationId: GetListener
      consumes: []
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        
        
      responses:
        200:
          description: Listener created
          schema:
            $ref: '#/definitions/HL7MessageListener'
            
          
        500:
          description: Server error
          
      
    put:
      tags:
      - Listeners
      summary: Updates a listener
      description: Updates a listener specified by the given id.
      operationId: PutListener
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        
        
      - name: listener
        in: body
        
        schema:
          $ref: '#/definitions/HL7MessageListener'
          
      responses:
        200:
          description: Updated listener
          
        400:
          description: Mismatch between passed id and listener id
          schema:
            $ref: '#/definitions/ProblemDetails'
            
          
        500:
          description: Server error
          
      
    delete:
      tags:
      - Listeners
      summary: Deletes a listener
      description: Deletes a listener.
      operationId: DeleteListener
      consumes: []
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        
        
      responses:
        200:
          description: Listener deleted
          schema:
            $ref: '#/definitions/HL7MessageListener'
            
          
        500:
          description: Server error
          
      
    
  /api/Logs:
    get:
      tags:
      - Logs
      operationId: Get
      consumes: []
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: Success
          
      
    
  /api/Logs/in/{seconds}:
    get:
      tags:
      - Logs
      summary: Get list of all logs with in a timespan of give senconds.
      operationId: GetWithin
      consumes: []
      produces:
      - application/json
      parameters:
      - name: seconds
        in: path
        description: Specify number of seconds, to retrieve all recent logs logged in the timespan.
        required: true
        type: integer
        
        
      responses:
        200:
          description: Success
          
      
    
  /api/Status/healthcheck:
    get:
      tags:
      - Status
      operationId: HealthCheck
      consumes: []
      produces: []
      parameters: []
      responses:
        200:
          description: Success
          
      
    
  /api/Status/version:
    get:
      tags:
      - Status
      operationId: Version
      consumes: []
      produces: []
      parameters: []
      responses:
        200:
          description: Success
          
      
    
definitions:
  HL7MessageListener:
    type: object
    properties:
      id:
        
        type: integer
        
      ipAddress:
        type: string
        
      port:
        
        type: integer
        
      name:
        type: string
        
      status:
        
        enum:
        - Idle
        - Listening
        type: integer
        
    example:
      id: 1
      iPAddress: 0.0.0.0
      port: 50500
      name: Test HL7
    
  ProblemDetails:
    type: object
    properties:
      type:
        type: string
        
      title:
        type: string
        
      status:
        
        type: integer
        
      detail:
        type: string
        
      instance:
        type: string
        
    additionalProperties:
      type: object
      
    

